/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateInstancePayload {
    #[serde(rename = "instance_key", skip_serializing_if = "Option::is_none")]
    pub instance_key: Option<String>,
    #[serde(rename = "webhook_url", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
}

impl CreateInstancePayload {
    pub fn new() -> CreateInstancePayload {
        CreateInstancePayload {
            instance_key: None,
            webhook_url: None,
        }
    }
}


