/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileUpload {
    #[serde(rename = "direct_path")]
    pub direct_path: String,
    #[serde(rename = "file_enc_sha256")]
    pub file_enc_sha256: Vec<i32>,
    #[serde(rename = "file_length")]
    pub file_length: i32,
    #[serde(rename = "file_sha256")]
    pub file_sha256: Vec<i32>,
    #[serde(rename = "media_key")]
    pub media_key: Vec<i32>,
    #[serde(rename = "mime_type")]
    pub mime_type: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl FileUpload {
    pub fn new(direct_path: String, file_enc_sha256: Vec<i32>, file_length: i32, file_sha256: Vec<i32>, media_key: Vec<i32>, mime_type: String, url: String) -> FileUpload {
        FileUpload {
            direct_path,
            file_enc_sha256,
            file_length,
            file_sha256,
            media_key,
            mime_type,
            url,
        }
    }
}


