/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupUpdateParticipantsPayload {
    #[serde(rename = "participants", skip_serializing_if = "Option::is_none")]
    pub participants: Option<Vec<String>>,
}

impl GroupUpdateParticipantsPayload {
    pub fn new() -> GroupUpdateParticipantsPayload {
        GroupUpdateParticipantsPayload {
            participants: None,
        }
    }
}


