/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListSection {
    #[serde(rename = "rows")]
    pub rows: Vec<crate::models::ListItem>,
    #[serde(rename = "title")]
    pub title: String,
}

impl ListSection {
    pub fn new(rows: Vec<crate::models::ListItem>, title: String) -> ListSection {
        ListSection {
            rows,
            title,
        }
    }
}


