/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LocationMessagePayloadLocation {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "latitude")]
    pub latitude: f32,
    #[serde(rename = "longitude")]
    pub longitude: f32,
    #[serde(rename = "name")]
    pub name: String,
}

impl LocationMessagePayloadLocation {
    pub fn new(latitude: f32, longitude: f32, name: String) -> LocationMessagePayloadLocation {
        LocationMessagePayloadLocation {
            address: None,
            latitude,
            longitude,
            name,
        }
    }
}


