/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReplyButton {
    #[serde(rename = "button_id", skip_serializing_if = "Option::is_none")]
    pub button_id: Option<String>,
    #[serde(rename = "button_text", skip_serializing_if = "Option::is_none")]
    pub button_text: Option<String>,
}

impl ReplyButton {
    pub fn new() -> ReplyButton {
        ReplyButton {
            button_id: None,
            button_text: None,
        }
    }
}


