/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructsPeriodUserInfoPayload {
    #[serde(rename = "user_ids")]
    pub user_ids: Vec<String>,
}

impl StructsPeriodUserInfoPayload {
    pub fn new(user_ids: Vec<String>) -> StructsPeriodUserInfoPayload {
        StructsPeriodUserInfoPayload {
            user_ids,
        }
    }
}


