/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructsPeriodButtonMessagePayload {
    #[serde(rename = "buttons", skip_serializing_if = "Option::is_none")]
    pub buttons: Option<Vec<crate::models::StructsPeriodReplyButton>>,
    #[serde(rename = "footer_text", skip_serializing_if = "Option::is_none")]
    pub footer_text: Option<String>,
    #[serde(rename = "header_text", skip_serializing_if = "Option::is_none")]
    pub header_text: Option<String>,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
}

impl StructsPeriodButtonMessagePayload {
    pub fn new() -> StructsPeriodButtonMessagePayload {
        StructsPeriodButtonMessagePayload {
            buttons: None,
            footer_text: None,
            header_text: None,
            text: None,
            to: None,
        }
    }
}


