/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructsPeriodListSection {
    #[serde(rename = "rows")]
    pub rows: Vec<crate::models::StructsPeriodListItem>,
    #[serde(rename = "title")]
    pub title: String,
}

impl StructsPeriodListSection {
    pub fn new(rows: Vec<crate::models::StructsPeriodListItem>, title: String) -> StructsPeriodListSection {
        StructsPeriodListSection {
            rows,
            title,
        }
    }
}


