/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructsPeriodGroupCreatePayload {
    #[serde(rename = "group_name", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    #[serde(rename = "participants", skip_serializing_if = "Option::is_none")]
    pub participants: Option<Vec<String>>,
}

impl StructsPeriodGroupCreatePayload {
    pub fn new() -> StructsPeriodGroupCreatePayload {
        StructsPeriodGroupCreatePayload {
            group_name: None,
            participants: None,
        }
    }
}


