/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructsPeriodListMessagePayload {
    #[serde(rename = "button_text", skip_serializing_if = "Option::is_none")]
    pub button_text: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "multi_select", skip_serializing_if = "Option::is_none")]
    pub multi_select: Option<bool>,
    #[serde(rename = "sections")]
    pub sections: Vec<crate::models::StructsPeriodListSection>,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "to")]
    pub to: String,
}

impl StructsPeriodListMessagePayload {
    pub fn new(sections: Vec<crate::models::StructsPeriodListSection>, to: String) -> StructsPeriodListMessagePayload {
        StructsPeriodListMessagePayload {
            button_text: None,
            description: None,
            multi_select: None,
            sections,
            text: None,
            title: None,
            to,
        }
    }
}


