/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructsPeriodGroupUpdateDescriptionPayload {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl StructsPeriodGroupUpdateDescriptionPayload {
    pub fn new() -> StructsPeriodGroupUpdateDescriptionPayload {
        StructsPeriodGroupUpdateDescriptionPayload {
            description: None,
        }
    }
}


