/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructsPeriodWebhookPayload {
    #[serde(rename = "webhook_url", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
}

impl StructsPeriodWebhookPayload {
    pub fn new() -> StructsPeriodWebhookPayload {
        StructsPeriodWebhookPayload {
            webhook_url: None,
        }
    }
}


