/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructsPeriodTemplateButton {
    /// Make sure this is unique
    #[serde(rename = "button_id", skip_serializing_if = "Option::is_none")]
    pub button_id: Option<String>,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
    /// Valid types are replyButton, urlButton & callButton
    #[serde(rename = "type")]
    pub r#type: String,
}

impl StructsPeriodTemplateButton {
    pub fn new(title: String, r#type: String) -> StructsPeriodTemplateButton {
        StructsPeriodTemplateButton {
            button_id: None,
            payload: None,
            title,
            r#type,
        }
    }
}


