/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TemplateButtonWithMediaPayload {
    #[serde(rename = "buttons")]
    pub buttons: Vec<crate::models::TemplateButton>,
    #[serde(rename = "content_text", skip_serializing_if = "Option::is_none")]
    pub content_text: Option<String>,
    #[serde(rename = "footer", skip_serializing_if = "Option::is_none")]
    pub footer: Option<String>,
    #[serde(rename = "media")]
    pub media: Box<crate::models::FileUpload>,
    #[serde(rename = "to")]
    pub to: String,
}

impl TemplateButtonWithMediaPayload {
    pub fn new(buttons: Vec<crate::models::TemplateButton>, media: crate::models::FileUpload, to: String) -> TemplateButtonWithMediaPayload {
        TemplateButtonWithMediaPayload {
            buttons,
            content_text: None,
            footer: None,
            media: Box::new(media),
            to,
        }
    }
}


