/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TemplateButtonPayload {
    #[serde(rename = "buttons")]
    pub buttons: Vec<crate::models::TemplateButton>,
    #[serde(rename = "content_text", skip_serializing_if = "Option::is_none")]
    pub content_text: Option<String>,
    #[serde(rename = "footer", skip_serializing_if = "Option::is_none")]
    pub footer: Option<String>,
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<String>,
    #[serde(rename = "to")]
    pub to: String,
}

impl TemplateButtonPayload {
    pub fn new(buttons: Vec<crate::models::TemplateButton>, to: String) -> TemplateButtonPayload {
        TemplateButtonPayload {
            buttons,
            content_text: None,
            footer: None,
            header: None,
            to,
        }
    }
}


